### ISSUE TITLE
Only works with localhost. Really?

### ISSUE THREAD

**Issue by 0xicl33n** [tsileo/pycgminer#3]
pycgminer.py:

    try:
        sock.connect((self.host, self.port))
        payload = {"command": command}

Should have something like

    m_IP = "ip.address here"
    m_PORT = "some port"
    if not m_IP,m_PORT:
        try:
            sock.connect((m_IP, m_PORT))
            #rest of try code
    else:                               #if no miner specified, assume localhost
        try:
             sock.connect((self.host, self.port))
             #rest of try code
         

Which would be great if it could be made callable like this:

    from pycgminer import CgminerAPI
    cgminer = CgminerAPI()
    cgminer.m_IP = "ip_addresss"
    cgminer.m_PORT = 4028

I should fork and experiment, but im lazy :/

EDIT: Upon further inspection it looks like the two things `self.host` and `self.port` are defined above. I am bad with classes, does that mean we CAN do `cgminer.host = blah `

or what?

**Comment by tsileo** [comment]
```python
from pycgminer import CgminerAPI

cgminer = CgminerAPI("ip_address", 4028)
```
